services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile.frontend
    environment:
      REACT_APP_API_URL: http://192.168.4.115:5050/api
    ports:
      - '3000:3000'
    networks:
      app-network:
        ipv4_address: 172.20.0.30

  backend:
    build: 
      context: .
      dockerfile: server/Dockerfile.backend
    ports: 
      - '5050:5050'
    networks:
      app-network:
        ipv4_address: 172.20.0.31

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"
